### ISSUE TITLE
Zero contents in main ode file

### ISSUE THREAD

**Issue by pgleeson** [ModelDBRepository/2015414#1]
Only file: https://github.com/ModelDBRepository/2015414/blob/main/dopa_gaba_glyc_eneuro.ode is empty...

**Comment by ramcdougal** [comment]
Fixed by @polinaovchinnikova in [7651dbf](https://github.com/ModelDBRepository/2015414/commit/7651dbf3d7bc0fab3aa3f3c953952a22e42e3cec)
